name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config liblxc-dev

      - name: Install modules
        run: make deps

      - name: Run build
        run: |
          make test-build
          make build

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config liblxc-dev

      - name: Install modules
        run: make deps

      - name: Run unit tests
        run: make test-unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config liblxc-dev

      - name: Install modules
        run: make deps

      - name: Run integration tests
        run: make test-integration
